import Logo from "./components/Logo";
import Navigation from "./components/Navigation";

export const metadata = {
	title: "Oasis",
	description: "Generated by Next.js",
};

export default function RootLayout ({ children}) {
	return (
		<html lang="eng">
			<body>
				<header>
					<Logo />
					<Navigation />
				</header>
				
				<main>{children}</main>
				<footer>Copyright</footer>
			</body>
		</html>
	)
}